version: '3.8'
services:
  postgres:
    restart: always
    image: postgres:16-alpine3.19
    #                     Max. connection        Increasing memory usage    Realy on SO to write    Do not wait for write      Accepting data           Checkpoint for wal
    #                     allowed to the max     or shared buffers         on wal                  on wall                    corruption               in 1 day
    command: 'postgres -c max_connections=151 -c shared_buffers=64MB    -c fsync=off            -c synchronous_commit=off  -c full_page_writes=off -c checkpoint_timeout=1d'
    volumes:
      - ./configs/init.pgsql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pwd
      POSTGRES_DB: user_db
    healthcheck:
      test: pg_isready -d user_db -U user_user
      interval: 10s
      timeout: 1s
      retries: 1000
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "420MB"
    networks:
      - rinha

  api1: &api
    restart: always
    build: .
    security_opt:
      # By default, Docker team do not allow Linux's io_uring because some vunerabilites
      # was found in the past.
      # See (https://github.com/moby/moby/pull/46762) for more information.
      # However, it is safe to use in a webserver enviroment since if some one can
      # access your server to run another process inside this container, you had been
      # pwned anyway. I felt that Docker team was over conservative in this decision.
      # Docker is a development and sysadmin tool and should had an easiest way to
      # enable Linux's io_uring.
      - seccomp:./configs/io_uring_seccomp.json 
    hostname: api01
    depends_on:
      postgres:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    deploy:
      resources:
        limits:
          cpus: "0.125"
          memory: "40MB" 
    networks:
      - rinha
    healthcheck:
      test: curl -s "http://localhost:9999/ping"
      interval: 1s
      timeout: 1s
      retries: 100

  api2:
    <<: *api

  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    ports:
      - "9999:9999"
    ulimits:
      nofile:
        soft: 4096
        hard: 4096
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"
    networks:
      - rinha

networks:
  rinha:
