version: '3.8'
services:
  postgres:
    restart: always
    image: postgres:16-alpine3.19
    volumes:
      - ./init.pgsql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pwd
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"

    healthcheck:
      test: pg_isready -d user_db -U user_user
      interval: 1s
      timeout: 1s
      retries: 1000
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "200MB"